#!/bin/bash
#v1.3
#open function:
	if [ "$1" = "open" ]; then
		open ~/.xbin
#list function:
	elif [ "$1" = "-ls" ]; then
		echo ":: xbin: list:"
		ls ~/.xbin
#load function:
	elif [ "$1" = "-l" ]; then
		if [ -e ~/.xbin/$2 ]; then
			echo ":: xbin: error"
		else
			sudo mv $2 ~/.xbin/$2
			echo ":: xbin: $2 loaded"
		fi
#remove function:
	elif [ "$1" = "-r" ]; then
		if [ -e ~/.xbin/$2 ]; then
			sudo mv ~/.xbin/$2 ~/$2
			echo ":: xbin: $2 removed"
		else
			echo ":: xbin: error"
		fi
#delete function:
	elif [ "$1" = "-del" ]; then
		if [ -e ~/.xbin/$2 ]; then
			sudo rm ~/.xbin/$2
			echo ":: xbin: $2 deleted"
		else
			echo ":: xbin: error"
		fi
#convert function:
	elif [ "$1" = "-c" ]; then
		file_name=$(echo $2 | cut -f 1 -d '.')
		sudo cp ~/$2 ~/$file_name
		sudo chmod +x ~/$file_name
		echo ":: xbin: $file_name converted"
#help function:
	elif [ "$1" = "help" ]; then
		echo ":: xbin: help:"
		cat ~/.xbin/resources/help.txt
		echo
	else
		echo ":: xbin: unknown input, please see help"
	fi
