#!/bin/bash
#v1.4
#open function:
	if [ "$1" = "open" ]; then
		open ~/.xbin
#list function:
	elif [ "$1" = "-ls" ]; then
		echo ":: xbin: list:"
		ls ~/.xbin
#load function:
	elif [ "$1" = "-l" ]; then
		if [ -e ~/.xbin/$2 ]; then
			echo ":: xbin: error"
		else
			path=`pwd`
			sudo mv $path/$2 ~/.xbin/$2
			if [ -e ~/.xbin/$2 ]; then
				echo ":: xbin: $2 loaded"
			else
				echo ":: xbin: error"
			fi
		fi
#remove function:
	elif [ "$1" = "-r" ]; then
		if [ -e ~/.xbin/$2 ]; then
			path=`pwd`
			sudo mv ~/.xbin/$2 $path/$2
			if [ -e $path/$2 ]; then
				echo ":: xbin: $2 removed"
			else
				echo ":: xbin: error"
			fi
		else
			echo ":: xbin: error"
		fi
#delete function:
	elif [ "$1" = "-del" ]; then
		if [ -e ~/.xbin/$2 ]; then
			sudo rm ~/.xbin/$2
			echo ":: xbin: $2 deleted"
		else
			echo ":: xbin: error"
		fi
#convert function:
	elif [ "$1" = "-c" ]; then
		path=`pwd`
		file_name=$(echo $2 | cut -f 1 -d '.')
		sudo cp $path/$2 $path/$file_name
		sudo chmod +x $path/$file_name
		if [ -e $path/$file_name ]; then
			echo ":: xbin: $file_name converted"
		else
			echo ":: xbin: error"
		fi
#help function:
	elif [ "$1" = "help" ]; then
		echo ":: xbin: help:"
		cat ~/.xbin/resources/help.txt
		echo
	else
		echo ":: xbin: unknown input, please see help"
	fi
